language: bash
services: docker

env:
  - VERSION=8.34.0
  
install:
  - git clone https://github.com/manios/docker-rsyslog.git

before_script:
  - env | sort
  - image="rsyslog:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run -d --name myrsyslog manios/rsyslog:"$VERSION"
  - docker rm -f myrsyslog

# vim:set et ts=2 sw=2:
