language: bash
services: docker

env:
  - VERSION=8.39.0
  
install:
  - git clone https://github.com/manios/docker-rsyslog.git

before_script:
  - env | sort
  - image="manios/rsyslog:$VERSION"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
  - docker run -d --name myrsyslog "$image"
  - docker run -it --rm "$image" rsyslogd -v
  - docker run -it --rm "$image" lognormalizer -V
  - docker rm -f myrsyslog

# vim:set et ts=2 sw=2:
